name: mcscan-blast-binderized
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.*
  - scipy
  - numpy
  - last
  - pandas-datareader>=0.5.0
  - biopython
  - seaborn
  - statsmodels
  - regex
  - blast>=2.7.1
  - perl=5.22.0.1
  - pip:
    - jcvi
    - gffutils
    - papermill
    - wand
    - matplotlib
